### PR TITLE
Two new quotes

### PR DESCRIPTION
**Pull request by Bayo19**

### CODE REVIEW

**Comment by odaynasser** [comment]
when are these gonna be merged? lol we gotta keep this repo updated with ye's quotes

**Comment by Bayo19** [comment]
that's what I was thinking. I think my additions were approved. Does this
mean I merge them? I'm new to git/hub

**Comment by ajzbc** [comment]
I'm going to go through all the pull requests and issues in a few or so. I'm busy with finals right now.

**Comment by Bayo19** [comment]
alright!

**Comment by ajzbc** [comment]
I have decided to move the quotes to an external file outside the master branch
[https://github.com/ajzbc/kanye.rest/tree/quotes](https://github.com/ajzbc/kanye.rest/tree/quotes)
Please make a new pull request :)

**Pull request closed without merging**
